### PR TITLE
Add shapely.geometry.polygon.orient to __all__, bug #722

### LINKED ISSUE #722: 'orient' is not declared in __all__
When I import the [`orient`](https://shapely.readthedocs.io/en/latest/manual.html#shapely.geometry.polygon.orient) function as:
```python
from shapely.geometry.polygon import orient
```
PyCharm highlights it for me with the following message:
```
'orient' is not declared in __all__
```
image

I assume it was simply overlooked and should be added to `__all__`. (Or maybe it would be better to remove `__all__` completely as wild card imports are bad practice.)

---

Shapely version: 1.6.4.post1, installed from conda.

### PR DESCRIPTION
**Pull request by quassy**
Fixes #722.

### CODE REVIEW

**Comment by idanmiara** [comment]
related to https://github.com/shapely/shapely/pull/1690

**Comment by quassy** [comment]
Any update on this?

**Comment by mwtoews** [comment]
Apologies for the slowness! Happy to provide a review now.

Shouldn't `orient` be added to `__all__` in [`shapely/geometry/polygon.py`](https://github.com/shapely/shapely/blob/main/shapely/geometry/polygon.py#L13) instead of `shapely/geometry/__init__.py`?

**Comment by quassy** [comment]
I have added it there, I think it belongs in both.

**Comment by mwtoews** [comment]
Why does it need to be added to both modules? It's [documented](https://shapely.readthedocs.io/en/stable/manual.html#shapely.geometry.polygon.orient) as part of the `shapely.geometry.polygon` module, since it applies to Polygon geometries. Adding `orient` to multiple modules is a bit confusing.

**Comment by quassy** [comment]
When it's documented like that I agree. 

For me it was a bit confusing that Polygon, LinearRing are both added to `shapely.geometry.polygon`, `shapely.geometry` and `shapely` (which is the documented location).

**Comment by mwtoews** [comment]
True, Polygon and some other classes are in `__all__` for a few modules. But to resolve this issue, it just needs to be defined once in `shapely/geometry/polygon.py`. This PR only needs to roll-back changes to `shapely/geometry/__init__.py` and it should be good to go.

**Comment by quassy** [comment]
Accidentally closed this PR by renaming the branch (thanks GitHub), so there is now a follow-up that should do exactly as required.

**Pull request closed without merging**
