### PR TITLE
PERF: vectorized implementation for signed area

### PR DESCRIPTION
**Pull request by whophil**
As discussed in #1315 

1. Vectorizes `shapely.algorithms.cga.signed_area`
2. Modifies `shapely.polygon.orient` to use `LinearRing.is_ccw` instead of `shapely.algorithms.cga.signed_area` to detect the handedness of rings. This defers to a fast GEOS call when possible.

### CODE REVIEW

**Comment by whophil** [comment]
@jorisvandenbossche this is ready for review. Thanks!

**Review by jorisvandenbossche — COMMENTED** [review]
Thanks for the PR, looks good to me!

There is one potential downside in using `is_ccw` for orient, and that is for invalid geometries. I don't know to what extent we want to ensure those are properly handled. But from reading the GEOS comments about this (https://github.com/shapely/shapely/issues/1315#issuecomment-1037108201), that is a case where the signed area check is more robust. 
I am wondering if it would be worth doing a `is_valid` check, and only then using `is_ccw`, and otherwise the `signed_area` version. It might well be that the combined `is_valid`/`is_ccw` is still faster.

**Comment by whophil** [comment]
As an alternative, geos offers `Algorithm::isCCWArea` (public)
https://github.com/libgeos/geos/blob/13a3bbb015f82c4458fb7768fd24fc6231a11367/src/algorithm/Orientation.cpp#L137-L142

It also seems that geos offers `Area::ofRingSigned` (public), so the Shapely implementation in `shapely.algorithm.cga` could probably just go away entirely if you wanted to use that instead.

**Comment by jorisvandenbossche** [comment]
> As an alternative, geos offers Algorithm::isCCWArea (public)

That's in the C++ API, while we use the (more stable) C API. So if we want to use that, it first requires a change in GEOS to expose this. 

I actually have been thinking it might be nice if GEOS would provide the whole "orient" functionality (but that's a longer term thought, not relevant for this PR now)

**Comment by jorisvandenbossche** [comment]
@whophil sorry for the slow follow-up! I updated it with latest main branch, and limited it to just the signed_area improvement, which we can certainly merge now.

**Comment by whophil** [comment]
Thanks @jorisvandenbossche

**Pull request merged**
