### PR TITLE
BUG: enum.py renamed to _enum.py to avoid name clash with the built in `enum` module

### PR DESCRIPTION
**Pull request by idanmiara**
Closes https://github.com/shapely/shapely/issues/1693

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Renaming sounds good to me, but I would suggest using `_enum.py` instead of `shapely_enum.py`

**Comment by idanmiara** [comment]
> Renaming sounds good to me, but I would suggest using `_enum.py` instead of `shapely_enum.py`

oops, missed your comment. :)
Done.

**Comment by jorisvandenbossche** [comment]
Thanks for the update. Small left-over issue: you accidentally committed `shapely/msvcp140.dll`, can you remove that again? 

(and https://github.com/shapely/shapely/pull/1703 is now also merged to prevent that in the future ;))

**Comment by idanmiara** [comment]
> Thanks for the update. Small left-over issue: you accidentally committed `shapely/msvcp140.dll`, can you remove that again?
> 
> (and #1703 is now also merged to prevent that in the future ;))

Sure😄, now fixed and rebased. 
Thanks !

**Comment by idanmiara** [comment]
Thanks @jorisvandenbossche

**Pull request merged**
