### PR TITLE
CI: Enable Python 3.11, update used actions

### PR DESCRIPTION
**Pull request by EwoutH**
Enables the Python 3.11 job, and updates the used checkout, setup-python and cache actions to their latest versions.

### CODE REVIEW

**Comment by EwoutH** [comment]
The CI [passes](https://github.com/EwoutH/shapely/actions/runs/3215933245) on my fork.

**Review by jorisvandenbossche — APPROVED** [review]
Thanks!

**Comment by EwoutH** [comment]
Thanks for merging! Should some of it also be implemented on the maint-1.8 branch?

**Comment by jorisvandenbossche** [comment]
> Should some of it also be implemented on the maint-1.8 branch?

Yes, that's welcome

**Pull request merged**
