### PR TITLE
Add Python 3.10 wheels for additional platforms

### PR DESCRIPTION
**Pull request by adamjstewart**
See #1348 for discussion.

If this works on maint-1.8 I'll submit the same PR to main.

@kvashchuka @mwtoews @sgillies @jorisvandenbossche

### CODE REVIEW

**Comment by adamjstewart** [comment]
Yay, everything passes! I'm guessing these skips were simply inadvertently copied from pygeos as @jorisvandenbossche surmised.

**Review by mwtoews — APPROVED** [review]
Tests on the new wheels look good!

**Review by caspervdw — COMMENTED** [review]
Thanks for the PR! I noticed that the `cp310-manylinux_i686` build is actually building numpy from source. I tend to avoid that situation and leave in the skip for that specific platform.

https://github.com/shapely/shapely/runs/6084981342?check_suite_focus=true#step:8:5601

**Comment by adamjstewart** [comment]
Works for me, re-added.

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
Thanks @adamjstewart ! 
(do you want to open a PR with the same change applied to the `main` branch? Otherwise I can also get to it)

**Pull request merged**
