### PR TITLE
Add support for geopackagebinary format loads/dumps

### PR DESCRIPTION
**Pull request by bradh**
This is described in the OGC GeoPackage spec (12-128r9). Its like
WKB, but with some extra noise (including the SRID) on the front.

### CODE REVIEW

**Comment by DavidMStraub** [comment]
@bradh, looking for a working Python implementation of a Geopackage binary parser, this PR is the only thing I found. Did you contribute this code to some other package eventually?

**Comment by bradh** [comment]
No. Noone wantes wanted it.

**Comment by achapkowski** [comment]
Encourage geomet to re-address it.  I was trying to get it in there too. :)

**Comment by bradh** [comment]
I respect the maintainers call. We might like the feature, but they have have to carry the overhead.

**Pull request closed without merging**
