### PR TITLE
Add Python 3.10 wheels for additional platforms

### PR DESCRIPTION
**Pull request by adamjstewart**
Forward-port of #1367 

@jorisvandenbossche

### CODE REVIEW

**Comment by adamjstewart** [comment]
Not sure why tests are failing...

**Comment by mwtoews** [comment]
This is the line that causes the failure: https://github.com/shapely/shapely/blob/fc55006ecac8ad7835fe1618d6d391bfe076403c/.github/workflows/release.yml#L135

(arm64 macos-10.15 does not fail due to message "Warning: While arm64 wheels can be built on x86_64, they cannot be tested. The ability to test the arm64 wheels will be added in a future release of cibuildwheel, once Apple Silicon CI runners are widely available.")

This line should probably just ` CIBW_TEST_COMMAND: pytest`

**Comment by jorisvandenbossche** [comment]
Yeah, there is actually a PR that is fixing up the wheel building the main branch (and eg is fixing that pytest invocation): https://github.com/shapely/shapely/pull/1253. I will try to get that merged first.

**Comment by jorisvandenbossche** [comment]
@adamjstewart I merged https://github.com/shapely/shapely/pull/1253, so you should be able to update this.

**Comment by adamjstewart** [comment]
Alright, GitHub Actions now passes! Travis CI is still failing, but it's also failing on main.

**Review by jorisvandenbossche — APPROVED** [review]
Thanks!

**Pull request merged**
