### PR TITLE
Make MultiPolygon accept polygons without holes

### PR DESCRIPTION
**Pull request by mdczaplicki**

### CODE REVIEW

**Comment by mwtoews** [comment]
Thanks, this is an old bug!

A shapely 2 workaround is to use `shapely.multipolygons(coords2)`, which seems to work fine.

**Comment by mdczaplicki** [comment]
That's what I'm using in the code. But it bothered me that I can't use the main API of the package.

**Comment by mwtoews** [comment]
Agree @mdczaplicki that this should be fixed for main API. I've added a few commits to get it ready. I'll backport it for the next 2.0 micro release after this is reviewed and merged (the doc changes need to be moved to the 2.0.2 section).

**Review by jorisvandenbossche — APPROVED** [review]
Thanks, looking good!

**Comment by mwtoews** [comment]
Backported to `maint-2.0` with 732370c93725136d8990bd26cc35e19ac8fdfd4f

**Pull request merged**
