### PR TITLE
Allow passing len-1 array for x and y coordinates in Point(..) (compat with 1.8)

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Closes https://github.com/shapely/shapely/issues/1587

### CODE REVIEW

**Comment by martinfleis** [comment]
I think that this has introduced a regression geopandas CI is now picking - https://github.com/geopandas/geopandas/actions/runs/3351235289/jobs/5552549617

**Comment by martinfleis** [comment]
GeoPandas CI fails on this

```py
Point([(2, 3), (11, 4), (7, 2), (8, 9), (1, 13)])
```

Which I'd say is a correct behaviour. I don't really understand what is the intention of this line. Shapely 1.8 creates `POINT (2 3)` but I'd say that raising `ValueError: Invalid values passed to Point constructor`, which is the behaviour of 2.0b2 is correct. But it should be noted, that it is a change of behaviour.

**Comment by jorisvandenbossche** [comment]
@martinfleis thanks for the note. I am also unsure why this behaviour existed that way, and I think it is a good change. But a change indeed, so will add it to the release notes.

**Comment by jorisvandenbossche** [comment]
-> https://github.com/shapely/shapely/pull/1600

**Pull request merged**
