### PR TITLE
ENH: Add concave_hull() function

### PR DESCRIPTION
**Pull request by gahjelle**
GEOS introduces a `GEOSConcaveHull()` function in v3.11. This PR adds a `shapely` binding.

(Contributed during EuroSciPy 2022 sprints in Basel)

Closes https://github.com/shapely/shapely/issues/1296

### CODE REVIEW

**Comment by gahjelle** [comment]
Docs are still missing.

**Comment by jorisvandenbossche** [comment]
@gahjelle I rebased this and added a test for the keyword arguments (and a small fix for it)

I seem to remember you started on a section for the user guide, but you didn't finish / push that yet? 
Now, I think this is certainly already in a good state (it has API docs), so I would propose to merge this as is, and certainly feel free to still open a follow-up PR with those docs (even if you don't find it finished).

**Comment by gahjelle** [comment]
@jorisvandenbossche Thanks a lot for cleaning this up and bringing it to completion!

I started looking at the extra documentation but didn't really do much there yet.

**Comment by jorisvandenbossche** [comment]
Thanks again!

**Pull request merged**
