### PR TITLE
Fix compatibility with numpy 2.1 dev to cast GeometryType to int as ufunc input

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Fixes https://github.com/shapely/shapely/issues/2098

### CODE REVIEW

**Review by mwtoews — APPROVED** [review]
Agree this is the correct cast type, and is consistent with other ufunc enums.

After merge, this should be cherry-picked into `maint-2.0` to resolve CI failures too.

**Comment by EwoutH** [comment]
It's a bit weird that NumPy 2.1 breaks stuff right, as a minor release?

**Comment by EwoutH** [comment]
If all else is not feasible, could we set NumPy to <2.1 on the 2.0 branch and sprint a release out?

https://github.com/shapely/shapely/blob/2a839056e91ec7d35e108404d0bfa16d9f3f8038/pyproject.toml#L46

**Comment by orthorhombic** [comment]
NumPy just released 2.1.0, and I noticed this impacting my code. It would be nice to get a release out.

@EwoutH - Impressive that you guessed "NumPy could release 2.1 at any moment" <4 hours before they released it.

**Comment by EwoutH** [comment]
What’s the strangest is that @jorisvandenbossche added this to the [2.0.6](https://github.com/shapely/shapely/milestone/58) milestone over two weeks ago, but 2.0.6 was never released.

**Comment by axelande** [comment]
Will 2.0.6 be released or what is missing from that being released?

**Comment by jorisvandenbossche** [comment]
> What’s the strangest is that @jorisvandenbossche added this to the [2.0.6](https://github.com/shapely/shapely/milestone/58) milestone over two weeks ago, but 2.0.6 was never released.

That's because milestones are used for future releases ;)

We were planning to cut a 2.0.6 release if needed (if numpy 2.1 was released before a next shapely release), which is the case now, so will try to do that the coming hours.

**Comment by jorisvandenbossche** [comment]
Shapely 2.0.6 is released (it's on pypi, conda-forge can still take a few hours)

**Pull request merged**
